import React from 'react'
import Header from '../components/home/header'
import Nft from '../components/nfts/Nft'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const nft = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>XTELPT</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='bg-[#252525] h-vh w-full flex-1'>
                <Header />
                <Nft />
            </div>
        </div>
    )
}

export default nft